// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEJ0weeI8AMKMg0W49rmb0wUPP9SDbmOM',
    appId: '1:312274445301:web:fb5ee2c0e5c83c989736bc',
    messagingSenderId: '312274445301',
    projectId: 'devfest-22-vizag',
    authDomain: 'devfest-22-vizag.firebaseapp.com',
    storageBucket: 'devfest-22-vizag.appspot.com',
    measurementId: 'G-01PCDWG1VE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo8MjML9vhmNMAmHxiDHks2ztDAa2l1Iw',
    appId: '1:312274445301:android:869fc1045c87032b9736bc',
    messagingSenderId: '312274445301',
    projectId: 'devfest-22-vizag',
    storageBucket: 'devfest-22-vizag.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt7Iw2tadlf8tw8ADKMO9dLhnk_Mdum1s',
    appId: '1:312274445301:ios:38da6f17b9f83fa29736bc',
    messagingSenderId: '312274445301',
    projectId: 'devfest-22-vizag',
    storageBucket: 'devfest-22-vizag.appspot.com',
    iosClientId: '312274445301-qc5eonqngali2jgi6s0c06avflqr4gg3.apps.googleusercontent.com',
    iosBundleId: 'com.google.devfestVizag',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt7Iw2tadlf8tw8ADKMO9dLhnk_Mdum1s',
    appId: '1:312274445301:ios:38da6f17b9f83fa29736bc',
    messagingSenderId: '312274445301',
    projectId: 'devfest-22-vizag',
    storageBucket: 'devfest-22-vizag.appspot.com',
    iosClientId: '312274445301-qc5eonqngali2jgi6s0c06avflqr4gg3.apps.googleusercontent.com',
    iosBundleId: 'com.google.devfestVizag',
  );
}
